package com.dev.akash.DataJpa.mail;

import java.util.Random;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Component;

@Component
public class MailConfig {

	@Autowired
	public JavaMailSender javaMailSender;


	public String forgotPassword(String email)
	{
		char[] otp = new char[6];
		Random obj = new Random();
		String to = email;

		for(int i= 0;i<6;i++) {
			otp[i]  = (char)(obj.nextInt(10)+48);
		}
		
		String otp1 = new String(otp);

		SimpleMailMessage message = new SimpleMailMessage();
		message.setTo(to);
		message.setSubject("This OTP is generated by Java Spring Boot");
		message.setText("Your One Time Password is : "+otp1+" Valid for 5 min only.");

		javaMailSender.send(message);

		return otp1;
	

	}



	/*
	 * public String sendMail() {
	 * 
	 * SimpleMailMessage message = new SimpleMailMessage();
	 * 
	 * message.setTo("ask4sayali@gmail.com");
	 * message.setSubject("This is system generated mail by Java Spring Boot");
	 * message.setText("Good Night");
	 * 
	 * javaMailSender.send(message);
	 * 
	 * return "Mail Sent";
	 * 
	 * }
	 */




}
